#!/bin/sh
set -e

chmod a+w -R /var/www/html/storage/logs
chmod a+w -R /var/www/html/storage/framework
chmod a+w -R /var/www/html/storage/app

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
